services:
  frontend:
    build: ./frontend-service
    ports:
      - "5000:5000"
    depends_on:
      - project-service
      - stats-service

  project-service:
    build: ./project-service
    ports:
      - "8000:8000"

  stats-service:
    build: ./stats-service
    ports:
      - "8001:8001"

  auth-service:
    build: ./auth-service
    ports:
      - "8002:8002"
