services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    networks:
      - backend
    ports:
      - "8002:8002"

  project-service:
    build: ./project-service
    container_name: project-service
    networks:
      - backend
    ports:
      - "8000:8000"

  stats-service:
    build: ./stats-service
    container_name: stats-service
    networks:
      - backend
    depends_on:
      - auth-service
      - project-service
    ports:
      - "8001:8001"

  frontend:
    build: ./frontend-service
    container_name: frontend
    networks:
      - backend
    depends_on:
      - auth-service
      - project-service
      - stats-service
    environment:
      AUTH_API: "http://auth-service:8002"
      PROJECT_API: "http://project-service:8000"
      STATS_API: "http://stats-service:8001"
    ports:
      - "5000:5000"

networks:
  backend:
